#define HOSTNAME "YOUR_DEVICE_HOSTNAME"

#define MQTT_LIGHT_COMMAND_TOPIC "YOUR_MQTT_COMMAND_TOPIC"
#define MQTT_LIGHT_STATUS_TOPIC "YOUR_MQTT_STATUS_TOPIC"
#define MQTT_MOTION_STATUS_TOPIC "YOUR_MQTT_MOTION_STATUS_TOPIC"

#define INITIAL_STATE "ON"
